name: continuous-deployment

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
      - run: yarn lint
      # Deploy this site to Netlify. This will fail if you don't have the netlify app installed -
      # either install it (see the CI failure message for a url) or comment this out if you don't want automatic deployment.
      - name: Deploy to Netlify
        id: deploy-netlify
        uses: netlify/actions/build@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NETLIFY_CMD: yarn install --frozen-lockfile && yarn build
          NETLIFY_DIR: ./build/
